# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/other/Constraints.xdc

# Block Designs: bd/mem/mem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mem || ORIG_REF_NAME==mem} -quiet] -quiet

# IP: bd/mem/ip/mem_blk_mem_gen_0_0/mem_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mem_blk_mem_gen_0_0 || ORIG_REF_NAME==mem_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/student/Documents/lab1/lab1.gen/sources_1/bd/mem/mem_ooc.xdc
